//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnazijaKM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan
    {
        public int ClanId { get; set; }
        public string Ime { get; set; }
        public int RedniBroj { get; set; }
        public int TimId { get; set; }
    
        public virtual Tim Tim { get; set; }
    }
}
