//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnazijaKM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMessage
    {
        public int ID { get; set; }
        public string PunoIme { get; set; }
        public string Email { get; set; }
        public string Tema { get; set; }
        public string Poruka { get; set; }
        public System.DateTime Poslato { get; set; }
    }
}
