//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnazijaKM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JezickiSmer
    {
        public int Id { get; set; }
        public string Slika1 { get; set; }
        public string Slika2 { get; set; }
        public string Slika3 { get; set; }
        public string Slika4 { get; set; }
        public string Opis { get; set; }
    }
}
