//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnazijaKM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maturanti
    {
        public int MaturantID { get; set; }
        public string Generacija { get; set; }
        public string Opis { get; set; }
        public string SlikaPath { get; set; }
    }
}
