//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnazijaKM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GimnazijaDBEntities : DbContext
    {
        public GimnazijaDBEntities()
            : base("name=GimnazijaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<Vesti> Vesti { get; set; }
        public virtual DbSet<Dogadjaji> Dogadjaji { get; set; }
        public virtual DbSet<Fajlovi> Fajlovi { get; set; }
        public virtual DbSet<ContactMessage> ContactMessages { get; set; }
        public virtual DbSet<Rasporedi> Rasporedi { get; set; }
        public virtual DbSet<Clan> Clan { get; set; }
        public virtual DbSet<Tim> Tim { get; set; }
        public virtual DbSet<Maturanti> Maturanti { get; set; }
        public virtual DbSet<JavneNabavke> JavneNabavke { get; set; }
        public virtual DbSet<Letopi> Letopis { get; set; }
        public virtual DbSet<Ekskurzije> Ekskurzije { get; set; }
        public virtual DbSet<Projekti> Projekti { get; set; }
        public virtual DbSet<JezickiSmer> JezickiSmer { get; set; }
        public virtual DbSet<MatematickiSmer> MatematickiSmer { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
    }
}
