//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnazijaKM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projekti
    {
        public int Id { get; set; }
        public string Tekst1 { get; set; }
        public string Tekst2 { get; set; }
        public string Tekst3 { get; set; }
        public string Tekst4 { get; set; }
        public string Tekst5 { get; set; }
        public string Slika1Path { get; set; }
        public string Slika2Path { get; set; }
        public string Slika3Path { get; set; }
        public string Slika4Path { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
