//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GimnazijaKM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vesti
    {
        public int Id { get; set; }
        public string Naslov { get; set; }
        public string KratakOpis { get; set; }
        public string PunOpis { get; set; }
        public string Slika1 { get; set; }
        public string Slika2 { get; set; }
        public string Slika3 { get; set; }
        public string Autor { get; set; }
        public string Kategorija { get; set; }
        public string Tag { get; set; }
        public Nullable<bool> Objavljeno { get; set; }
        public Nullable<System.DateTime> KreiranoU { get; set; }

        public string KreiranoUFormatted
        {
            get
            {
                return KreiranoU?.ToString("dd.MM.yyyy. HH:mm") ?? "N/A";
            }
        }
    }
}
